// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/imagestore/v1/imagestore.proto

package imagestorev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadImageRequest_Metadata
	//	*UploadImageRequest_Chunk
	Data          isUploadImageRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_imagestore_v1_imagestore_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImageRequest) GetData() isUploadImageRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadImageRequest) GetMetadata() *ImageMetadataInput {
	if x != nil {
		if x, ok := x.Data.(*UploadImageRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadImageRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadImageRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadImageRequest_Data interface {
	isUploadImageRequest_Data()
}

type UploadImageRequest_Metadata struct {
	Metadata *ImageMetadataInput `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadImageRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadImageRequest_Metadata) isUploadImageRequest_Data() {}

func (*UploadImageRequest_Chunk) isUploadImageRequest_Data() {}

type ImageMetadataInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageMetadataInput) Reset() {
	*x = ImageMetadataInput{}
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageMetadataInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMetadataInput) ProtoMessage() {}

func (x *ImageMetadataInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMetadataInput.ProtoReflect.Descriptor instead.
func (*ImageMetadataInput) Descriptor() ([]byte, []int) {
	return file_proto_imagestore_v1_imagestore_proto_rawDescGZIP(), []int{1}
}

func (x *ImageMetadataInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ImageMetadataInput) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ImageMetadataInput) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,3,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_imagestore_v1_imagestore_proto_rawDescGZIP(), []int{2}
}

func (x *UploadImageResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *UploadImageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadImageResponse) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *UploadImageResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type GetImageMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageMetadataRequest) Reset() {
	*x = GetImageMetadataRequest{}
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageMetadataRequest) ProtoMessage() {}

func (x *GetImageMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetImageMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_imagestore_v1_imagestore_proto_rawDescGZIP(), []int{3}
}

func (x *GetImageMetadataRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type ImageMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Width         int32                  `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	Url           string                 `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,10,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageMetadata) Reset() {
	*x = ImageMetadata{}
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMetadata) ProtoMessage() {}

func (x *ImageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMetadata.ProtoReflect.Descriptor instead.
func (*ImageMetadata) Descriptor() ([]byte, []int) {
	return file_proto_imagestore_v1_imagestore_proto_rawDescGZIP(), []int{4}
}

func (x *ImageMetadata) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ImageMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ImageMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ImageMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ImageMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ImageMetadata) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageMetadata) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageMetadata) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *ImageMetadata) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageMetadata) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_imagestore_v1_imagestore_proto_rawDescGZIP(), []int{5}
}

func (x *ListImagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListImagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListImagesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*ImageMetadata       `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_imagestore_v1_imagestore_proto_rawDescGZIP(), []int{6}
}

func (x *ListImagesResponse) GetImages() []*ImageMetadata {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ListImagesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListImagesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type DeleteImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImageRequest) Reset() {
	*x = DeleteImageRequest{}
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageRequest) ProtoMessage() {}

func (x *DeleteImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageRequest.ProtoReflect.Descriptor instead.
func (*DeleteImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_imagestore_v1_imagestore_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *DeleteImageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImageResponse) Reset() {
	*x = DeleteImageResponse{}
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageResponse) ProtoMessage() {}

func (x *DeleteImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageResponse.ProtoReflect.Descriptor instead.
func (*DeleteImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_imagestore_v1_imagestore_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteImageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetImageURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Thumbnail     bool                   `protobuf:"varint,2,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageURLRequest) Reset() {
	*x = GetImageURLRequest{}
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageURLRequest) ProtoMessage() {}

func (x *GetImageURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageURLRequest.ProtoReflect.Descriptor instead.
func (*GetImageURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_imagestore_v1_imagestore_proto_rawDescGZIP(), []int{9}
}

func (x *GetImageURLRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *GetImageURLRequest) GetThumbnail() bool {
	if x != nil {
		return x.Thumbnail
	}
	return false
}

type GetImageURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageURLResponse) Reset() {
	*x = GetImageURLResponse{}
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageURLResponse) ProtoMessage() {}

func (x *GetImageURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_imagestore_v1_imagestore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageURLResponse.ProtoReflect.Descriptor instead.
func (*GetImageURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_imagestore_v1_imagestore_proto_rawDescGZIP(), []int{10}
}

func (x *GetImageURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_imagestore_v1_imagestore_proto protoreflect.FileDescriptor

const file_proto_imagestore_v1_imagestore_proto_rawDesc = "" +
	"\n" +
	"$proto/imagestore/v1/imagestore.proto\x12\rimagestore.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"u\n" +
	"\x12UploadImageRequest\x12?\n" +
	"\bmetadata\x18\x01 \x01(\v2!.imagestore.v1.ImageMetadataInputH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"l\n" +
	"\x12ImageMetadataInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"\x86\x01\n" +
	"\x13UploadImageResponse\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12#\n" +
	"\rthumbnail_url\x18\x03 \x01(\tR\fthumbnailUrl\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"4\n" +
	"\x17GetImageMetadataRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\"\xc3\x02\n" +
	"\rImageMetadata\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\x05R\x06height\x12;\n" +
	"\vuploaded_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\x12\x10\n" +
	"\x03url\x18\t \x01(\tR\x03url\x12#\n" +
	"\rthumbnail_url\x18\n" +
	" \x01(\tR\fthumbnailUrl\"h\n" +
	"\x11ListImagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x93\x01\n" +
	"\x12ListImagesResponse\x124\n" +
	"\x06images\x18\x01 \x03(\v2\x1c.imagestore.v1.ImageMetadataR\x06images\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"H\n" +
	"\x12DeleteImageRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x13DeleteImageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x12GetImageURLRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1c\n" +
	"\tthumbnail\x18\x02 \x01(\bR\tthumbnail\"'\n" +
	"\x13GetImageURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xbf\x03\n" +
	"\fImageService\x12V\n" +
	"\vUploadImage\x12!.imagestore.v1.UploadImageRequest\x1a\".imagestore.v1.UploadImageResponse(\x01\x12X\n" +
	"\x10GetImageMetadata\x12&.imagestore.v1.GetImageMetadataRequest\x1a\x1c.imagestore.v1.ImageMetadata\x12Q\n" +
	"\n" +
	"ListImages\x12 .imagestore.v1.ListImagesRequest\x1a!.imagestore.v1.ListImagesResponse\x12T\n" +
	"\vDeleteImage\x12!.imagestore.v1.DeleteImageRequest\x1a\".imagestore.v1.DeleteImageResponse\x12T\n" +
	"\vGetImageURL\x12!.imagestore.v1.GetImageURLRequest\x1a\".imagestore.v1.GetImageURLResponseBHZFgithub.com/lautaroblasco23/imagestore/proto/imagestore/v1;imagestorev1b\x06proto3"

var (
	file_proto_imagestore_v1_imagestore_proto_rawDescOnce sync.Once
	file_proto_imagestore_v1_imagestore_proto_rawDescData []byte
)

func file_proto_imagestore_v1_imagestore_proto_rawDescGZIP() []byte {
	file_proto_imagestore_v1_imagestore_proto_rawDescOnce.Do(func() {
		file_proto_imagestore_v1_imagestore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_imagestore_v1_imagestore_proto_rawDesc), len(file_proto_imagestore_v1_imagestore_proto_rawDesc)))
	})
	return file_proto_imagestore_v1_imagestore_proto_rawDescData
}

var file_proto_imagestore_v1_imagestore_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_imagestore_v1_imagestore_proto_goTypes = []any{
	(*UploadImageRequest)(nil),      // 0: imagestore.v1.UploadImageRequest
	(*ImageMetadataInput)(nil),      // 1: imagestore.v1.ImageMetadataInput
	(*UploadImageResponse)(nil),     // 2: imagestore.v1.UploadImageResponse
	(*GetImageMetadataRequest)(nil), // 3: imagestore.v1.GetImageMetadataRequest
	(*ImageMetadata)(nil),           // 4: imagestore.v1.ImageMetadata
	(*ListImagesRequest)(nil),       // 5: imagestore.v1.ListImagesRequest
	(*ListImagesResponse)(nil),      // 6: imagestore.v1.ListImagesResponse
	(*DeleteImageRequest)(nil),      // 7: imagestore.v1.DeleteImageRequest
	(*DeleteImageResponse)(nil),     // 8: imagestore.v1.DeleteImageResponse
	(*GetImageURLRequest)(nil),      // 9: imagestore.v1.GetImageURLRequest
	(*GetImageURLResponse)(nil),     // 10: imagestore.v1.GetImageURLResponse
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_proto_imagestore_v1_imagestore_proto_depIdxs = []int32{
	1,  // 0: imagestore.v1.UploadImageRequest.metadata:type_name -> imagestore.v1.ImageMetadataInput
	11, // 1: imagestore.v1.ImageMetadata.uploaded_at:type_name -> google.protobuf.Timestamp
	4,  // 2: imagestore.v1.ListImagesResponse.images:type_name -> imagestore.v1.ImageMetadata
	0,  // 3: imagestore.v1.ImageService.UploadImage:input_type -> imagestore.v1.UploadImageRequest
	3,  // 4: imagestore.v1.ImageService.GetImageMetadata:input_type -> imagestore.v1.GetImageMetadataRequest
	5,  // 5: imagestore.v1.ImageService.ListImages:input_type -> imagestore.v1.ListImagesRequest
	7,  // 6: imagestore.v1.ImageService.DeleteImage:input_type -> imagestore.v1.DeleteImageRequest
	9,  // 7: imagestore.v1.ImageService.GetImageURL:input_type -> imagestore.v1.GetImageURLRequest
	2,  // 8: imagestore.v1.ImageService.UploadImage:output_type -> imagestore.v1.UploadImageResponse
	4,  // 9: imagestore.v1.ImageService.GetImageMetadata:output_type -> imagestore.v1.ImageMetadata
	6,  // 10: imagestore.v1.ImageService.ListImages:output_type -> imagestore.v1.ListImagesResponse
	8,  // 11: imagestore.v1.ImageService.DeleteImage:output_type -> imagestore.v1.DeleteImageResponse
	10, // 12: imagestore.v1.ImageService.GetImageURL:output_type -> imagestore.v1.GetImageURLResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_imagestore_v1_imagestore_proto_init() }
func file_proto_imagestore_v1_imagestore_proto_init() {
	if File_proto_imagestore_v1_imagestore_proto != nil {
		return
	}
	file_proto_imagestore_v1_imagestore_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadImageRequest_Metadata)(nil),
		(*UploadImageRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_imagestore_v1_imagestore_proto_rawDesc), len(file_proto_imagestore_v1_imagestore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_imagestore_v1_imagestore_proto_goTypes,
		DependencyIndexes: file_proto_imagestore_v1_imagestore_proto_depIdxs,
		MessageInfos:      file_proto_imagestore_v1_imagestore_proto_msgTypes,
	}.Build()
	File_proto_imagestore_v1_imagestore_proto = out.File
	file_proto_imagestore_v1_imagestore_proto_goTypes = nil
	file_proto_imagestore_v1_imagestore_proto_depIdxs = nil
}
